import fs from 'node:fs';
const p = 'D:/Zcode Project/gui4dsh/web/src/components/SetupWizard.tsx';
let s = fs.readFileSync(p, 'utf8');

const L = [];
L.push("/** Click-driven cloudflared flow: download, login (link surfaced here), quick tunnel with auto-scraped URL, named tunnel for a fixed address. */");
L.push('function CloudflarePanel({ onExternalUrl }: { onExternalUrl: (u: string) => void }) {');
L.push("  const { t } = useI18n();");
L.push('  const [st, setSt] = useState<{ installed?: boolean; loggedIn?: boolean; quickRunning?: boolean; quickUrl?: string; namedRunning?: boolean; loginUrl?: string } | null>(null);');
L.push("  const [busy, setBusy] = useState('');");
L.push("  const [hostname, setHostname] = useState('');");
L.push('  const call = async (path: string, tag: string, body?: unknown) => {');
L.push('    setBusy(tag);');
L.push('    try {');
L.push("      const r = await fetch('/api/fe/cfd/' + path, { method: 'POST', headers: { 'content-type': 'application/json', authorization: 'Bearer ' + (localStorage.getItem('g4d_token') || '') }, body: '{}' }).then((x) => x.json());");
L.push('      if (r && r.ok === false && r.error) useStore.getState().toast(\'error\', r.error);');
L.push('      return r;');
L.push('    } finally {');
L.push("      setBusy('');");
L.push('    }');
L.push('  };');
L.push('  const refresh = async () => {');
L.push('    try {');
L.push("      const r = await fetch('/api/fe/cfd/status', { headers: { authorization: 'Bearer ' + (localStorage.getItem('g4d_token') || '') } }).then((x) => x.json());");
L.push('      setSt(r);');
L.push("      if (r.quickUrl && r.quickRunning) onExternalUrl(r.quickUrl);");
L.push('    } catch { /* ignore */ }');
L.push('  };');
L.push('  useEffect(() => {');
L.push('    void refresh();');
L.push('    const iv = setInterval(refresh, 3000);');
L.push('    return () => clearInterval(iv);');
L.push('    // eslint-disable-next-line react-hooks/exhaustive-deps');
L.push('  }, []);');
L.push('  return (');
L.push('    <div style={{ border: \'1px solid var(--border)\', borderRadius: 8, padding: 10 }}>');
L.push("      <div style={{ fontSize: 12.5, fontWeight: 700 }}>{t('wizard.cfTitle')}</div>");
L.push("      <div className=\"hint\" style={{ marginTop: 2 }}>{t('wizard.cfHint')}</div>");
L.push('');
L.push('      {/* install */}');
L.push('      {!st?.installed ? (');
L.push('        <div style={{ display: \'flex\', gap: 8, marginTop: 8, alignItems: \'center\' }}>');
L.push('          <button className="btn sm primary" disabled={!!busy} onClick={() => void call(\'install\', \'install\')}>');
L.push("            {busy === 'install' ? t('cf.downloading') : t('cf.install')}");
L.push('          </button>');
L.push("          <span className=\"hint\">{t('cf.installHint')}</span>");
L.push('        </div>');
L.push('      ) : (');
L.push("        <div className=\"hint\" style={{ marginTop: 6 }}>{t('cf.installed')} ✓</div>");
L.push('      )}');
L.push('');
L.push('      {/* quick tunnel */}');
L.push('      <div style={{ marginTop: 10, borderTop: \'1px dashed var(--border)\', paddingTop: 8 }}>');
L.push("        <div style={{ fontSize: 12.5, fontWeight: 600 }}>{t('cf.quickTitle')}</div>");
L.push("        <div className=\"hint\">{t('cf.quickHint')}</div>");
L.push('        <div style={{ display: \'flex\', gap: 8, marginTop: 6, alignItems: \'center\', flexWrap: \'wrap\' }}>');
L.push('          {!st?.quickRunning ? (');
L.push("            <button className=\"btn sm primary\" disabled={!!busy || !st?.installed} onClick={() => void call('quick/start', 'quick')}>{busy === 'quick' ? t('common.loading') : t('cf.quickStart')}</button>");
L.push('          ) : (');
L.push("            <button className=\"btn sm\" onClick={() => void call('quick/stop', '')}>{t('cf.quickStop')}</button>");
L.push('          )}');
L.push('          {st?.quickRunning && st?.quickUrl && (');
L.push('            <span className="badge green">');
L.push('              <a href={st.quickUrl} target="_blank" rel="noreferrer" style={{ color: \'inherit\' }}>{st.quickUrl}</a>');
L.push('            </span>');
L.push('          )}');
L.push('          {st?.quickRunning && !st?.quickUrl && <span className="hint">{t('cf.waitingUrl')}</span>}');
L.push('        </div>');
L.push('        {st?.quickRunning && st?.quickUrl && <div className="hint" style={{ marginTop: 4 }}>{t('cf.autoSaved')}</div>}');
L.push('      </div>');
L.push('');
L.push('      {/* fixed address */}');
L.push('      <div style={{ marginTop: 10, borderTop: \'1px dashed var(--border)\', paddingTop: 8 }}>');
L.push("        <div style={{ fontSize: 12.5, fontWeight: 600 }}>{t('cf.fixedTitle')}</div>");
L.push("        <div className=\"hint\">{t('cf.fixedHint')}</div>");
L.push('        {!st?.loggedIn ? (');
L.push('          <div style={{ display: \'flex\', gap: 8, marginTop: 6, alignItems: \'center\', flexWrap: \'wrap\' }}>');
L.push("            <button className=\"btn sm\" disabled={!!busy || !st?.installed} onClick={() => void call('login', 'login')}>{t('cf.login')}</button>");
L.push('            {st?.loginUrl && (');
L.push('              <a href={st.loginUrl} target="_blank" rel="noreferrer" className="btn sm primary" style={{ textDecoration: \'none\' }}>{t('cf.loginGo')} ↗</a>');
L.push('            )}');
L.push("            {st?.installed && <span className=\"hint\">{t('cf.loginHint')}</span>}");
L.push('          </div>');
L.push('        ) : (');
L.push('          <>');
L.push("            <div className=\"hint\" style={{ marginTop: 4 }}>{t('cf.loggedIn')} ✓</div>");
L.push('            <div style={{ display: \'flex\', gap: 6, marginTop: 6, alignItems: \'center\' }}>');
L.push('              <input className="input" style={{ flex: 1 }} placeholder="dsh.example.com" value={hostname} onChange={(e) => setHostname(e.target.value.trim())} />');
L.push("              <button className=\"btn sm\" disabled={!hostname} onClick={() => void call('named/create', 'named', { hostname })}>{busy === 'named' ? t('common.loading') : t('cf.bind')}</button>");
L.push('            </div>');
L.push('            <div style={{ display: \'flex\', gap: 8, marginTop: 6, alignItems: \'center\' }}>');
L.push('              {!st?.namedRunning ? (');
L.push("                <button className=\"btn sm primary\" disabled={!!busy} onClick={() => void call('named/run', 'run')}>{t('cf.run')}</button>");
L.push('              ) : (');
L.push("                <button className=\"btn sm\" onClick={() => void call('named/stop', '')}>{t('cf.stop')}</button>");
L.push('              )}');
L.push('              {st?.namedRunning && hostname && (');
L.push('                <span className="badge green">');
L.push('                  <a href={\'https://\' + hostname} target="_blank" rel="noreferrer" style={{ color: \'inherit\' }}>{\'https://\' + hostname}</a>');
L.push('                </span>');
L.push('              )}');
L.push('            </div>');
L.push('          </>');
L.push('        )}');
L.push('      </div>');
L.push('    </div>');
L.push('  );');
L.push('}');
const panel = L.join('\n');

const exp = 'export function SetupWizard';
s = s.replace(exp, panel + '\n\n' + exp);

// replace the old route B block: from its opening div to the closing of the cfFixed details structure
const start = s.indexOf("        {/* route B: cloudflare tunnel */}");
if (start < 0) throw new Error('route B start missing');
// the block ends right before the closing of the zero-cost card: find the LAST '</details>' after start, then the following '</div>\n        </div>' hmm — locate by the card end marker
const endMarker = '      </div>\n\n      {/* ---------- Step 2: FRP ---------- */}';
const end = s.indexOf(endMarker, start);
if (end < 0) throw new Error('route B end missing');
const replacement = '        <CloudflarePanel onExternalUrl={(u) => { setProbeUrl(u); void fe.saveSettings({ externalBaseUrl: u }); onSaved(); }} />\n';
s = s.slice(0, start) + replacement + s.slice(end);
fs.writeFileSync(p, s);
console.log('cloudflare panel swapped');
